"""
export.py — PDF report generation and CSV export helpers.
Supports both Plotly figures (via kaleido) and fallback matplotlib.
"""

import io
import pandas as pd


def generate_pdf(
    figures: list,
    stats: dict,
    asset_name: str = "BTC",
    bench_name: str = "ETH",
    days: int = 365,
) -> bytes:
    """
    Generate a multi-page PDF report from Plotly figures.

    Parameters
    ----------
    figures : list of Plotly Figure objects.
    stats : dict of computed statistics.
    asset_name, bench_name, days : metadata for the title page.

    Returns
    -------
    bytes — PDF file content.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_pdf import PdfPages

    buf = io.BytesIO()

    with PdfPages(buf) as pdf:
        # ── Title / summary page ───────────────────────────────────────
        fig_title, ax = plt.subplots(figsize=(8.5, 11))
        ax.axis("off")

        title_text = f"Crypto Beta Analytics Report\n{asset_name} vs {bench_name} · {days} days"
        ax.text(0.5, 0.92, title_text, transform=ax.transAxes,
                fontsize=20, fontweight="bold", ha="center", va="top")

        # Stats table
        bp = stats.get("breusch_pagan", {})
        stat_lines = [
            f"Beta (β):  {stats.get('beta', 'N/A'):.4f}",
            f"Alpha (α):  {stats.get('alpha', 'N/A'):.6f}",
            f"R²:  {stats.get('r_squared', 'N/A'):.4f}",
            f"95% CI:  [{stats.get('beta_ci_lower', 'N/A'):.4f}, {stats.get('beta_ci_upper', 'N/A'):.4f}]",
            f"p-value:  {stats.get('p_value', 'N/A'):.2e}",
            "",
            f"{asset_name} Sharpe:  {stats.get('asset_sharpe', 'N/A'):.2f}",
            f"{bench_name} Sharpe:  {stats.get('benchmark_sharpe', 'N/A'):.2f}",
            f"{asset_name} Max DD:  {stats.get('asset_max_dd', 'N/A'):.1%}",
            f"{asset_name} VaR (95%):  {stats.get('asset_var_95', 'N/A'):.2%}",
            f"{asset_name} CVaR (95%):  {stats.get('asset_cvar_95', 'N/A'):.2%}",
            "",
            f"Treynor:  {stats.get('treynor', 'N/A'):.4f}",
            f"Jensen's α:  {stats.get('jensens_alpha', 'N/A'):.4%}",
            "",
            f"Breusch-Pagan p:  {bp.get('p_value', 'N/A'):.4f}" if bp else "",
            f"Heteroscedastic:  {'Yes' if bp.get('heteroscedastic') else 'No'}" if bp else "",
        ]

        stats_text = "\n".join(stat_lines)
        ax.text(0.5, 0.72, stats_text, transform=ax.transAxes,
                fontsize=11, ha="center", va="top", family="monospace",
                bbox=dict(boxstyle="round,pad=0.5", facecolor="#f0f0f0", alpha=0.8))

        ax.text(0.5, 0.05, "Generated by Crypto Beta Analytics",
                transform=ax.transAxes, fontsize=8, ha="center",
                color="grey", style="italic")

        pdf.savefig(fig_title)
        plt.close(fig_title)

        # ── Chart pages (convert Plotly → image → matplotlib → PDF) ───
        for fig in figures:
            try:
                # Plotly figure → PNG bytes via kaleido
                img_bytes = fig.to_image(format="png", width=1200, height=600, scale=2)
                from PIL import Image
                img = Image.open(io.BytesIO(img_bytes))

                fig_page, ax_page = plt.subplots(figsize=(11, 5.5))
                ax_page.axis("off")
                ax_page.imshow(img, aspect="auto")
                pdf.savefig(fig_page, bbox_inches="tight")
                plt.close(fig_page)
            except Exception:
                # Fallback: skip figure if conversion fails
                continue

    buf.seek(0)
    return buf.read()


def to_csv_bytes(df: pd.DataFrame) -> bytes:
    """Convert DataFrame to CSV bytes for download."""
    return df.to_csv().encode("utf-8")
