"""
export.py — PDF report generation and CSV export helpers.
"""

import io
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


def generate_pdf(
    figures: list[plt.Figure],
    stats: dict,
    asset_name: str = "BTC",
    bench_name: str = "ETH",
    days: int = 365,
) -> bytes:
    """
    Generate a multi-page PDF report.

    Parameters
    ----------
    figures : list of matplotlib Figure objects to include.
    stats : dict of computed statistics.
    asset_name, bench_name, days : metadata for the title page.

    Returns
    -------
    bytes — PDF file content.
    """
    buf = io.BytesIO()

    with PdfPages(buf) as pdf:
        # ── Title / summary page ───────────────────────────────────────
        fig_title, ax = plt.subplots(figsize=(8.5, 11))
        ax.axis("off")

        title_text = f"Crypto Beta Analytics Report\n{asset_name} vs {bench_name} · {days} days"
        ax.text(0.5, 0.92, title_text, transform=ax.transAxes,
                fontsize=20, fontweight="bold", ha="center", va="top")

        # Stats table
        bp = stats.get("breusch_pagan", {})
        stat_lines = [
            f"Beta (β):  {stats.get('beta', 'N/A'):.4f}",
            f"Alpha (α):  {stats.get('alpha', 'N/A'):.6f}",
            f"R²:  {stats.get('r_squared', 'N/A'):.4f}",
            f"95% CI:  [{stats.get('beta_ci_lower', 'N/A'):.4f}, {stats.get('beta_ci_upper', 'N/A'):.4f}]",
            f"p-value:  {stats.get('p_value', 'N/A'):.2e}",
            "",
            f"{asset_name} Sharpe:  {stats.get('asset_sharpe', 'N/A'):.2f}",
            f"{bench_name} Sharpe:  {stats.get('benchmark_sharpe', 'N/A'):.2f}",
            f"{asset_name} Max DD:  {stats.get('asset_max_dd', 'N/A'):.1%}",
            f"{asset_name} VaR (95%):  {stats.get('asset_var_95', 'N/A'):.2%}",
            f"{asset_name} CVaR (95%):  {stats.get('asset_cvar_95', 'N/A'):.2%}",
            "",
            f"Breusch-Pagan p:  {bp.get('p_value', 'N/A'):.4f}" if bp else "",
            f"Heteroscedastic:  {'Yes' if bp.get('heteroscedastic') else 'No'}" if bp else "",
        ]

        stats_text = "\n".join(stat_lines)
        ax.text(0.5, 0.72, stats_text, transform=ax.transAxes,
                fontsize=11, ha="center", va="top", family="monospace",
                bbox=dict(boxstyle="round,pad=0.5", facecolor="#f0f0f0", alpha=0.8))

        ax.text(0.5, 0.05, "Generated by Crypto Beta Analytics",
                transform=ax.transAxes, fontsize=8, ha="center",
                color="grey", style="italic")

        pdf.savefig(fig_title)
        plt.close(fig_title)

        # ── Chart pages ────────────────────────────────────────────────
        for fig in figures:
            pdf.savefig(fig, bbox_inches="tight")

    buf.seek(0)
    return buf.read()


def to_csv_bytes(df: pd.DataFrame) -> bytes:
    """Convert DataFrame to CSV bytes for download."""
    return df.to_csv().encode("utf-8")
